version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      APP_ENV: "dev"

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
